import {Command, flags} from '@oclif/command'
import * as fs from 'fs'
import SidebarFixer from '../lib/SidebarFixer'

export default class FixSidebar extends Command {
  static description = 'Updates the sidebar menu in html files generated by mdBook by reading it from an index.html file that has the desired menu and replacing the menu in the other files.'

  static flags = {
    version: flags.version({char: 'v'}),
    help: flags.help({char: 'h'}),

    sourcePath: flags.string({char: 's', description: 'path-to-source-folder', required: true}),
    destPath: flags.string({char: 'd', description: 'path-to-destination-folder', required: true}),
  }

  static args = []

  async run() {
    const {flags} = this.parse(FixSidebar)

    // not expecting any args
    // if (args) {
    //   this.error(`fix-sidebar does not take raw arguments`, {exit: 2})
    // }

    if (!fs.existsSync(flags.sourcePath)) {
      this.error(`Source folder does not exist: ${flags.sourcePath}`, {exit: 2})
    }

    if (!fs.existsSync(flags.destPath)) {
      this.error(`Destination folder does not exist: ${flags.destPath}`, {exit: 2})
    }

    const fixer = new SidebarFixer(flags.sourcePath, flags.destPath)

    const fileCount = fixer.updateSidebars()
    this.log(`${fileCount} file${fileCount === 1 ? '' : 's'} updated.`)
  }
}
